[package]
name = "ip-route-proc-macro"
description = "Embed iproute2-like commands into your program"
version.workspace = true
authors = [ "Remy D. Farley <one-d-wide@protonmail.com>" ]
categories = [ "network-programming", "os", "api-bindings" ]
repository = "https://github.com/one-d-wide/netlink-bindings"
license = "MIT OR Apache-2.0"
edition = "2024"

[lib]
path = "lib.rs"
proc-macro = true

[features]
coverage = [ "ip-route-syntax/coverage" ]

[dependencies]
ip-route-syntax.workspace = true

ipnet = "2"

quote = "1"
proc-macro2 = "1"
scopeguard = "1"

syn = { version = "3.0", features = [ "full", "derive", "parsing", "visit-mut" ] }
