[package]
name = "ip-route-syntax"
description = "Embed iproute2-like commands into your program"
version.workspace = true
authors = [ "Remy D. Farley <one-d-wide@protonmail.com>" ]
categories = [ "network-programming", "os", "api-bindings" ]
repository = "https://github.com/one-d-wide/netlink-bindings"
license = "MIT OR Apache-2.0"
edition = "2024"

[[bin]]
name = "interp-poc"
path = "interp-poc.rs"

[lib]
path = "lib.rs"

[features]
coverage = [ ]

[dependencies]
libc = "0"
ipnet = "2"

quote = "1"
proc-macro2 = "1"
scopeguard = "1"
